// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3kvqTsDOrdCqazunUc7IBPTpEgZUq0Fk',
    appId: '1:400405737762:web:525faecea6d2a21389357b',
    messagingSenderId: '400405737762',
    projectId: 'nectar-a9eda',
    authDomain: 'nectar-a9eda.firebaseapp.com',
    storageBucket: 'nectar-a9eda.firebasestorage.app',
    measurementId: 'G-MKWN5BQ58D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGq2JhUr-_0kcRoAfteRd-QNifGoWym40',
    appId: '1:400405737762:android:afb2a7ed4123daa089357b',
    messagingSenderId: '400405737762',
    projectId: 'nectar-a9eda',
    storageBucket: 'nectar-a9eda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV3rWCU41SmlNAkVmswxz-oSP0cnWRQ-4',
    appId: '1:400405737762:ios:90c7c09909b47c7c89357b',
    messagingSenderId: '400405737762',
    projectId: 'nectar-a9eda',
    storageBucket: 'nectar-a9eda.firebasestorage.app',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV3rWCU41SmlNAkVmswxz-oSP0cnWRQ-4',
    appId: '1:400405737762:ios:90c7c09909b47c7c89357b',
    messagingSenderId: '400405737762',
    projectId: 'nectar-a9eda',
    storageBucket: 'nectar-a9eda.firebasestorage.app',
    iosBundleId: 'com.example.nectar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3kvqTsDOrdCqazunUc7IBPTpEgZUq0Fk',
    appId: '1:400405737762:web:572d64b0bc83861489357b',
    messagingSenderId: '400405737762',
    projectId: 'nectar-a9eda',
    authDomain: 'nectar-a9eda.firebaseapp.com',
    storageBucket: 'nectar-a9eda.firebasestorage.app',
    measurementId: 'G-VNWG3LCL3W',
  );

}